name: docker-build

on:
  push:
    tags:
      - 'v*'

jobs:
  call-common:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/common.yml
    with:
      run-docker: true

  create-release:
    needs: call-common
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            README.md
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}