name: test-build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-common:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/common.yml
    with:
      run-docker: true
      metadata-tags: |
        type=raw,value=sha-${{ github.sha }}
